### ISSUE TITLE
不会判断 flutter 列表的最大滚动距离

### ISSUE THREAD

**Issue by zmtzawqlp** [YangLang116/fit_system_screenshot#1]
会一直滚动呢？ 是不是应该在 flutter 这边判断了，去通知下原生？

**Comment by YangLang116** [comment]
调整了长截屏策略，拉取最新代码试试，目前在小米、vivo、Oppo、华为等主流机型上，验证没发现问题

**Comment by zmtzawqlp** [comment]
这个最大滚动距离，用这种方式，局限很大呢？

**Comment by YangLang116** [comment]
通过[AfterLayout](https://book.flutterchina.club/chapter14/layout.html#_14-4-6-afterlayout) 可以获取Widget的高度，对于Sliver类型列表需要累加高度，有什么好的建议呢？

**Comment by zmtzawqlp** [comment]
一帧之后，通过 ScrollScrollControler 就能知道列表的高度了 . attachToPage 方法中，可以插件默认处理下


 ```
 double scrollLength = 0;
  @override
  void initState() {
    scrollController.addListener(() {
      if (scrollLength !=
          scrollController.position.maxScrollExtent +
              scrollController.position.viewportDimension) {
        scrollLength = scrollController.position.maxScrollExtent +
            scrollController.position.viewportDimension;
        fitSystemScreenshot.updateScrollLength(scrollLength);
      }
    });
}

```

**Comment by YangLang116** [comment]
可以把这个放到attachToPage中，对于NestedScrollView需要同时处理outerController、innerController。

**Comment by zmtzawqlp** [comment]
updateScrollLength 方法如果可以在任何时间调用的话，应该都不存在问题。 本来我还想说load more 的列表支持不
